=== shivamtyagi577/Web_Tecno-/LAB06/music.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT musiccollect (music+)>
<!ELEMENT music (musictopic,musicdesc,musicpara)>
<!ELEMENT musictopic (#PCDATA)>
<!ELEMENT musicdesc (#PCDATA)>
<!ELEMENT musicpara (#PCDATA)>
<!ATTLIST music musicId CDATA #REQUIRED>

=== shivamtyagi577/Web_Tecno-/LAB06/music.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="music.xsl"?>
<!DOCTYPE musiccollect SYSTEM "music.dtd">
<musiccollect>
<music musicId = "01">
    <musictopic>Most underrated move in 2021 offseason</musictopic>
    <musicdesc>A look at the biggest under-the-radar move for all 30 teams</musicdesc>
    <musicpara>The big moves get our attention, but sometimes it's the little ones that make the difference. The 2021 NBA offseason was filled with splashy signings and trades that saw some of the league's top talent find new surroundings. Be careful, however, not to discount the transactions made around the fringes.</musicpara>
</music>

<music musicId = "01">
    <musictopic>Most underrated move in 2021 offseason</musictopic>
    <musicdesc>A look at the biggest under-the-radar move for all 30 teams</musicdesc>
    <musicpara>The big moves get our attention, but sometimes it's the little ones that make the difference. The 2021 NBA offseason was filled with splashy signings and trades that saw some of the league's top talent find new surroundings. Be careful, however, not to discount the transactions made around the fringes.</musicpara>
</music>

<music musicId = "01">
    <musictopic>Most underrated move in 2021 offseason</musictopic>
    <musicdesc>A look at the biggest under-the-radar move for all 30 teams</musicdesc>
    <musicpara>The big moves get our attention, but sometimes it's the little ones that make the difference. The 2021 NBA offseason was filled with splashy signings and trades that saw some of the league's top talent find new surroundings. Be careful, however, not to discount the transactions made around the fringes.</musicpara>
</music>

<music musicId = "01">
    <musictopic>Most underrated move in 2021 offseason</musictopic>
    <musicdesc>A look at the biggest under-the-radar move for all 30 teams</musicdesc>
    <musicpara>The big moves get our attention, but sometimes it's the little ones that make the difference. The 2021 NBA offseason was filled with splashy signings and trades that saw some of the league's top talent find new surroundings. Be careful, however, not to discount the transactions made around the fringes.</musicpara>
</music>

<music musicId = "01">
    <musictopic>Most underrated move in 2021 offseason</musictopic>
    <musicdesc>A look at the biggest under-the-radar move for all 30 teams</musicdesc>
    <musicpara>The big moves get our attention, but sometimes it's the little ones that make the difference. The 2021 NBA offseason was filled with splashy signings and trades that saw some of the league's top talent find new surroundings. Be careful, however, not to discount the transactions made around the fringes.</musicpara>
</music>

</musiccollect>
